### ISSUE TITLE
0.2.0 segfault

### ISSUE THREAD

**Issue by fthx** [ubuntu-flutter-community/software#343]
Hi,

`snap-store                      0.2.0-alpha                 624       preview/edge`

does not start (segfault).

**Comment by Feichtmeier** [comment]
Hi, I can not reproduce this

![grafik](https://user-images.githubusercontent.com/15329494/193545641-245d8692-4ddf-4501-bdde-3f4bc5b8db34.png)

**Comment by fthx** [comment]
Ok I'll try after another reboot.
```
~$ snap-store
Erreur de segmentation (core dumped)
```

**Comment by fthx** [comment]
ok after a new reboot it does start. Odd.

```
~$ snap-store
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.118" (uid=1000 pid=3112 comm="/snap/snap-store/624/bin/software " label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=1505 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux._startListenConnectivity (package:connectivity_plus_linux/src/connectivity.dart:61)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.119" (uid=1000 pid=3112 comm="/snap/snap-store/624/bin/software " label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=1505 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux.checkConnectivity (package:connectivity_plus_linux/src/connectivity.dart:24)
<asynchronous suspension>

```

**Comment by Feichtmeier** [comment]
Ohhhh ok this might be related to

**Comment by Feichtmeier** [comment]
Maybe you're pc didn't had network for the first second of the start and it crashed. That's another reason to fix 202

**Comment by fthx** [comment]
Maybe related to my home network?
Often switches between two AP.
